apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - /hyperkube 
    - apiserver
    - --admission-control=NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota
    - --service-cluster-ip-range={{ service_cluster_ip_range }}
    - --allow-privileged=true
    - --insecure-bind-address=0.0.0.0
    - --etcd-servers={{ etcd_ep }}
    - --logtostderr=false 
    - --log-dir=/var/log/kubernetes
    image: {{ k8s_image }}
    name: kube-apiserver
    volumeMounts:
    - name: vol
      mountPath: /var/log/kubernetes
  volumes:
  - name: vol
    hostPath:
      path: /var/log/kubernetes
  hostNetwork: true
