---
## set all the hosts with common setting.
#- hosts: all
#  roles:
#  - common
#  tags:
#  - common
  
# make certs
- hosts: build
  roles:
  - certs
  tags:
  - certs
  vars_files:
    - group_vars/all.yml

# should make a choice of single or multy
- hosts: etcd
  roles:
  - etcd
  tags:
  - etcd
  vars_files:
    - group_vars/all.yml
  
## install flannel on every docker node
- hosts: k8smaster
  roles:
  - flannel
  tags:
  - flannel
  vars_files:
    - group_vars/all.yml
  
# install docker on every docker node
- hosts: k8smaster
  roles:
  - docker
  tags:
  - docker

# install k8smaster
- hosts: k8smaster
  roles:
  - kube179master
  tags:
  - kube179master
  vars_files:
    - group_vars/all.yml
