- name: stop firewalld
  service: name=firewalld state=stopped enabled=no
  
- name: stop selinux
  selinux: state=disabled

- name: remove all repo
  file: path=/etc/yum.repos.d/ state=absent
- file: path=/etc/yum.repos.d/ state=directory

- name: set yum repo
  copy: src=yum.repo dest=/etc/yum.repos.d/yum.repo
